apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-be
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: arc-be
spec:
  project: '{{.Values._argocdProjectName}}'
  source:
    repoURL: '{{.Values._gitRepoUrl}}'
    path: helm/prod/arc-be
    targetRevision: '{{.Values._gitTargetRevision}}'
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        microservice-chart:
          azure:
            workloadIdentityClientId: '{{.Values._azureWorkloadIdentityClientId}}'
          serviceAccount:
            create: false
            name: "cittadini-workload-identity"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: '{{.Values._namespace}}'
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 10
